### ISSUE TITLE
Enlever les routes "orders" inutiles

### ISSUE THREAD

**Issue by ngdo-pro** [wizaplace/starterkit#277]
Les controllers n'existent plus, il faudra penser à mettre à jour les routes en question dans les templates concernés.

```
# orders
order_all:
    path: /commandes
    defaults: { _controller: AppBundle:Order:viewOrders }
    methods: [GET]

order:
    path: /commande/{orderId}
    defaults: { _controller: AppBundle:Order:viewOrder }
    methods: [GET]

create_return:
    path: /commande/{orderId}/retour
    defaults: { _controller: AppBundle:Order:createReturn }
    methods: [POST]

create_return_form:
    path: /commande/{orderId}/retour
    defaults: { _controller: AppBundle:Order:displayCreateReturn }
    methods: [GET]
```
